---
title: "GSE185047"
output: html_document
date: "2023-11-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(GEOquery)
library(data.table)

load(here::here("data/ligand_receptor_db.RData")) ## run code/ligand_receptor_dbs.Rmd first
dbs_all = list(baderlab=baderlab, nichenet=nichenet, 
          fantom5=fantom5, citedb=citedb, all_dbs=all_dbs)

source(here::here("00-misc_funs/funcs.R"))

```

```{r}
# retrieve GEO dataset
geo_data <- "GSE185047"
geo <- readRDS(here::here("data/gse185047.rds"))
e1 <- geo[[paste0(geo_data, "_series_matrix.txt.gz")]]
phenoData <- pData(e1)
ann <- e1@featureData@data
ann <- ann[ann$`Gene Symbol` != "", ]
exp <- exprs(e1)
dim(phenoData); dim(ann); dim(exp);
all(rownames(phenoData) == colnames(exp))

# Subset for treatment
ifn_k <- subset(phenoData, `treatment:ch1` == "IFN-K" & `time point:ch1` %in% c("Dose 1 on Week 0", "Follow-up on Week 36") )
eset <- exp[rownames(ann), rownames(ifn_k)]
all(rownames(eset) == rownames(ann))

gensym <- sapply(strsplit(ann$`Gene Symbol`, "///"), trimws)
id_gensym <- data.table(gensym = unlist(gensym),
           probeids = rep(rownames(ann), sapply(gensym, length))) %>% 
  filter(gensym %in% unique(unlist(dbs_all)))

X = eset[id_gensym$probeids, ] %>% 
  as.data.frame() %>% 
  mutate(genesym = id_gensym$gensym) %>% 
  group_by(genesym) %>% 
  summarise(across(everything(), ~ mean(.x, na.rm=TRUE)))

eset <- as.matrix(X[,-1])
rownames(eset) <- X$genesym
y = ifn_k$`time point:ch1`
names(y) <- rownames(ifn_k)
obs_id = ifn_k$`patient:ch1`

# rm genes from db if not in eset
dbs <- lapply(dbs_all, function(db){
  db <- db[names(db) %in% rownames(eset)]
  db <- lapply(db, function(i){
    intersect(i, rownames(eset))
  })
  db[sapply(db, length) > 0]
})

```


# Run all methods

```{r}
# Fast GSEA, run GSEA for all datasets and rank
cores <- 4

funs <- list(cfgsea_p = cfgsea_p,
             cgsva_p = cgsva_p,
             cpca_p = cpca_p,
             cpcr_p = cpcr_p,
             cgsvar_p = cgsvar_p)

result <- run_all(eset, y, obs_id, dbs, cores, funs)
ranks <- lapply(result, function(db){
  100 - 100*round(sapply(db, function(ligand){ 
  k = which(names(ligand) == "IFNA2")
  ifelse(length(k) == 0, NA, k)})/sapply(db, length), 2)})
```

# save data

```{r}
do.call(rbind, ranks) %>% 
  as.data.frame() %>% 
  mutate(method = gsub("_p", "", rownames(.))) %>% 
  gather(database, rank, -method) %>% 
  mutate(method_db = paste(method, database, sep="_"),
         gse = "GSE185047",
         cytokine = "IFN-K",
         disease = "systemic lupus erythematosus",
         sample_size = ncol(eset),
         type = "anti-cytokine treatment",
         sample_type = "whole blood",
         platform_type = "microarray",
         platform = "Affymetrix Human Genome U133 Plus 2.0 Array") %>% 
  saveRDS(paste0("../results/",geo_data,".rds"))
```

