---
title: "Visualizations"
author: "Amrit Singh"
date: "2023-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## load data

```{r}
.list <- lapply(list.files(here::here("results"), full.names = TRUE), function(rds){
  readRDS(rds)
})

res <- do.call(rbind, .list) %>% mutate(cytokine = gsub("IFN-K", "IFNA2", cytokine))

```

## overall performance by method

```{r}
res %>% 
  group_by(method) %>% 
  summarise(mean = mean(rank, na.rm=TRUE), sd = sd(rank, na.rm = TRUE)) %>% 
  ggplot(aes(x = mean, y = reorder(method, mean), fill = method)) +
  geom_bar(stat = "identity", position = "dodge") + ylab("Method + Database Annotation")
```
```{r}
library(pheatmap)
df <- res %>% select(method, database, rank)
df$rank <- df$rank %>% replace_na(0)
rownames(df) <- df$method
pheatmap(df$rank)
```


## overall performance by database

```{r}
res %>% 
  group_by(database) %>% 
  summarise(mean = mean(rank, na.rm=TRUE), sd = sd(rank, na.rm = TRUE)) %>% 
  ggplot(aes(x = mean, y = reorder(database, mean), fill = database)) +
  geom_errorbar(aes(xmin=mean-1, xmax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
  geom_bar(stat = "identity", position = "dodge") + ylab("Method + Database Annotation")
```


## overall performance by method x database

```{r}
f1 <- res %>% 
  group_by(method_db) %>% 
  summarise(mean = mean(rank, na.rm=TRUE), sd = sd(rank, na.rm = TRUE),
            db = unique(database)) %>% 
  ggplot(aes(x = mean, y = reorder(method_db, mean), fill = db)) +
  geom_errorbar(aes(xmin=mean-1, xmax=mean+sd), width=.2,
               position=position_dodge(.9)) +
  geom_bar(stat = "identity", position = "dodge") + 
  ylab("Method + Database Annotation") +
  xlab("Mean Rank Across All Studies") +
  theme(axis.text=element_text(size=10), legend.text = element_text(size=8)) +
  scale_fill_brewer(palette = "Pastel1") +
  theme_classic()
```


## overall performance by method x database x cytokine

```{r}
res %>% 
  group_by(method_db, cytokine) %>% 
  summarise(mean = mean(rank, na.rm=TRUE), sd = sd(rank, na.rm = TRUE),
            db = unique(database)) %>%  
  ggplot(aes(x = reorder(method_db, mean), y = mean, fill = db)) +
  geom_bar(stat = "identity", position = "dodge") + 
  geom_errorbar(aes(ymin=mean-1, ymax=mean+sd), width=.2,
             position=position_dodge(.9)) +
  ylab("Mean Rank By Study/Cytokine") +
  xlab("Method + Database Annotation") +
  facet_wrap(~cytokine, ncol=1) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(axis.text=element_text(size=10), legend.text = element_text(size=8)) +
  scale_fill_brewer(palette = "Pastel1") +
  theme_classic() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 

```
```{r}
ggsave("../../poster/poster_files/figure-html/overall_performance-2.png", f1)
ggsave("../../poster/poster_files/figure-html/mean_performance_by_cytokine.png", f2)
```
# Create an overlap of ligand-receptor pairs between databases
```{r}
library(UpSetR)
load(here::here("data/ligand_receptor_db.RData")) ## run code/ligand_receptor_dbs.Rmd first
dbs_all = list(baderlab=baderlab, nichenet=nichenet, 
          fantom5=fantom5, citedb=citedb)
lapply(dbs_all, length)
lr <- lapply(dbs_all, names)
upset(fromList(lr))

```

