---
title: "pregnancy_multiomics_data"
author: "Jeffrey Tang"
date: "2024-05-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(data.table)
library(ggplotify)
library(here)
library(limma)

load(here::here("data/ligand_receptor_db.RData")) ## run code/ligand_receptor_dbs.Rmd first
dbs_all = list(baderlab=baderlab, nichenet=nichenet, 
          fantom5=fantom5, citedb=citedb, all_dbs=all_dbs)

source(here::here("code/funcs.R"))

```

```{r}
load(here::here("data/termpregnancymultiomics/Data.Rda"))

# RNA dataset for some reason is not filtered and normalized properly
# assume this is a raw counts matrix, turn the negative values into 0
eset_ghaemi_rna <- InputData[[1]] %>% 
  t() %>%
  as.data.frame() %>%
  mutate(across(everything(), ~if_else(. < 0, 0, .))) %>%
  as.matrix()

lib.size <- colSums(eset_ghaemi_rna)  
y <- t(log2(t(eset_ghaemi_rna + 0.5)/(lib.size + 1) * 1e+06))
y <- normalizeBetweenArrays(y)


eset_ghaemi_protein <- InputData[[2]] %>% t()

# remove 0 variance
eset_subset <- eset_ghaemi_rna[apply(eset_ghaemi_rna, 1, sd) > 0, ]

# do some wrangling for the metadata
# get week 1 and week 4 - check difference between week 1 vs postpartum
pregnancy_term_subset <- colnames(eset_subset)
split_names <- strsplit(pregnancy_term_subset, "_")
patient_ids <- sapply(split_names, `[`, 1)
weeks <- as.integer(sapply(split_names, `[`, 2))
metadata <- data.frame(Patient_ID = pregnancy_term_subset, Week = weeks)
metadata$Week <- paste0("week_",metadata$Week)
metadata_subset <- metadata %>% filter(Week == "week_1" | Week == "week_4")
pregnancy_term = metadata_subset$Week
names(pregnancy_term) <- metadata_subset$Patient_ID

#obs_id <- patient_ids


# rm genes from db if not in eset
dbs <- lapply(dbs_all, function(db){
  db <- db[names(db) %in% rownames(eset_subset)]
  db <- lapply(db, function(i){
    intersect(i, rownames(eset_subset))
  })
  db[sapply(db, length) > 0]
})

obs_id <- NULL

# subset RNA data to week 1 and week 4
eset_ghaemi_rna_subset <- 
  eset_subset[,colnames(eset_subset) %in% names(pregnancy_term)]

eset <- eset_ghaemi_rna_subset %>% 
  as_tibble() %>%
  pivot_longer(everything(), names_to = "pid", values_to = "values") 

```

```{r}
run_all = function(eset, y, obs_id, dbs, cores, funs){
  lapply(funs, function(fun) fun(eset, y, obs_id, dbs, cores))
}

cores <- 1

funs <- list(cfgsea_p = cfgsea_p,
             cgsva_p = cgsva_p,
             cpca_p = cpca_p,
             cpcr_p = cpcr_p,
             cgsvar_p = cgsvar_p)

result <- run_all(eset_ghaemi_rna_subset, 
                  y = pregnancy_term, 
                  obs_id, 
                  dbs, 
                  cores, 
                  funs)
```

